apiVersion: v1
kind: Service
# provide important information of a resource
metadata:
  name: login-app-service
spec:
  ports:
    - name: http
      # service expose port inside k8s cluster
      port: 10000
      # traffic to service exposing port will be forwarded to targetPort on the pods backing the Service
      targetPort: 8080
  # select group of pods to apply the above service rules
  selector:
    login.service: login-app
