version: '3'
services:
  login-db:
    container_name: login-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: login
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - penguin-network
  login-app:
    container_name: login-app
    build:
      context: .
      dockerfile: ./docker_setup/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      login-db:
        condition: service_started
    networks:
      - penguin-network
  login-mq:
    container_name: login-mq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - penguin-network
volumes:
  mysql-data:

networks:
  penguin-network: