version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: login_db
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - penguin-network
  login:
    build:
      context: ./
      dockerfile: ./docker_setup/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - penguin-network
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: your_rabbitmq_username
      RABBITMQ_DEFAULT_PASS: your_rabbitmq_password
volumes:
  mysql-data:

networks:
  penguin-network: