version: '3'
services:
  login_db:
    container_name: login_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: login
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - penguin-network
  login_app:
    container_name: login_app
    build:
      context: .
      dockerfile: ./docker_setup/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      login_db:
        condition: service_started
    networks:
      - penguin-network
  login_mq:
    container_name: login_mq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: your_rabbitmq_username
      RABBITMQ_DEFAULT_PASS: your_rabbitmq_password
    networks:
      - penguin-network
volumes:
  mysql-data:

networks:
  penguin-network: