server:
  port: 8080

spring:
  datasource:
#    database config is overridden by login-app-deployment.yaml, for local docker-compose testing only
#    url: jdbc:mysql://login-db:3306/login?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # [dev only] config for create table by annotation
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: login_mq
    port: 5672
    username: your_rabbitmq_username
    password: your_rabbitmq_password
    listener:
      simple:
        default-requeue-rejected: false

  security:
    jwt:
      secret: your_jwt_secret_key
      expiration-in-ms: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG