server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/login_db?allowPublicKeyRetrieval=true&useSSL=false
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: your_rabbitmq_username
    password: your_rabbitmq_password
    listener:
      simple:
        default-requeue-rejected: false

  security:
    jwt:
      secret: your_jwt_secret_key
      expiration-in-ms: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG